title: IT Support Helpdesk
logo: assets/img/headshot_circle.png
theme:  jekyll-theme-freelancer

# Site settings
email: kudzai.z@outlook.com
url: https://github.com/jeromelachaud/freelancer-theme
description: MY Portflio
skills: "Web Developer - Graphic Artist - User Experience Designer"
meta_author: Zvomuya Kudzai

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Build settings
markdown: kramdown
permalink: pretty

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

  contact: static

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
